services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ng
      POSTGRES_PASSWORD: ngpass
      ## store data inside this directory inside container
      PGDATA: /data/postgres

    ## attach volume to internal postgres storage. so data will be safely stored inside db even if our machine crashes
    volumes:
      - db:/data/postgres

    ## 5332: host url
    ## 5432 : host postgres always listens on
    ## we essentially map host url to postgres url
    ports:
      - "5332:5432"

    ## allow containers with same network to communicate
    networks:
      - db-net
    ## always restart unless we explicitly stop dockerfile
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db-net
    restart: unless-stopped

networks:
  db:
    driver: bridge
  db-net:
    driver: bridge
volumes:
  db: